package contracts

import "reflect"

// SchemaEntry describes one generated JSON Schema and matching generated
// reference doc entry.
type SchemaEntry struct {
	Key         string
	Group       string
	Path        string
	Title       string
	Description string
	Shape       string
	Type        reflect.Type
}

// SchemaRegistry returns the generated schema/doc registry entries for the
// current public contract surface.
func SchemaRegistry() []SchemaEntry {
	return []SchemaEntry{
		{
			Key:         "ui_resources.plan",
			Group:       "ui_resources",
			Path:        "schema/ui-resources/plan.schema.json",
			Title:       "Plan UI resource",
			Description: "Read-only JSON resource returned by `/api/plan` for `harness ui`.",
			Shape:       "output",
			Type:        reflect.TypeFor[PlanResult](),
		},
		{
			Key:         "ui_resources.review",
			Group:       "ui_resources",
			Path:        "schema/ui-resources/review.schema.json",
			Title:       "Review UI resource",
			Description: "Read-only JSON resource returned by `/api/review` for `harness ui`.",
			Shape:       "output",
			Type:        reflect.TypeFor[ReviewResult](),
		},
		{
			Key:         "ui_resources.timeline",
			Group:       "ui_resources",
			Path:        "schema/ui-resources/timeline.schema.json",
			Title:       "Timeline UI resource",
			Description: "Read-only JSON resource returned by `/api/timeline` for `harness ui`.",
			Shape:       "output",
			Type:        reflect.TypeFor[TimelineResult](),
		},
		{
			Key:         "commands.status.result",
			Group:       "command_results",
			Path:        "schema/commands/status.result.schema.json",
			Title:       "Status command result",
			Description: "JSON output for `harness status`.",
			Shape:       "output",
			Type:        reflect.TypeFor[StatusResult](),
		},
		{
			Key:         "commands.install.result",
			Group:       "command_results",
			Path:        "schema/commands/install.result.schema.json",
			Title:       "Install command result",
			Description: "JSON output for `harness install`.",
			Shape:       "output",
			Type:        reflect.TypeFor[InstallResult](),
		},
		{
			Key:         "commands.lifecycle.result",
			Group:       "command_results",
			Path:        "schema/commands/lifecycle.result.schema.json",
			Title:       "Lifecycle command result",
			Description: "Shared JSON output shape for lifecycle commands such as `harness execute start`, `harness archive`, `harness reopen`, `harness land`, and `harness land complete`.",
			Shape:       "output",
			Type:        reflect.TypeFor[LifecycleResult](),
		},
		{
			Key:         "commands.review.start.result",
			Group:       "command_results",
			Path:        "schema/commands/review.start.result.schema.json",
			Title:       "Review start command result",
			Description: "JSON output for `harness review start`.",
			Shape:       "output",
			Type:        reflect.TypeFor[ReviewStartResult](),
		},
		{
			Key:         "commands.review.submit.result",
			Group:       "command_results",
			Path:        "schema/commands/review.submit.result.schema.json",
			Title:       "Review submit command result",
			Description: "JSON output for `harness review submit`.",
			Shape:       "output",
			Type:        reflect.TypeFor[ReviewSubmitResult](),
		},
		{
			Key:         "commands.review.aggregate.result",
			Group:       "command_results",
			Path:        "schema/commands/review.aggregate.result.schema.json",
			Title:       "Review aggregate command result",
			Description: "JSON output for `harness review aggregate`.",
			Shape:       "output",
			Type:        reflect.TypeFor[ReviewAggregateResult](),
		},
		{
			Key:         "commands.evidence.submit.result",
			Group:       "command_results",
			Path:        "schema/commands/evidence.submit.result.schema.json",
			Title:       "Evidence submit command result",
			Description: "JSON output for `harness evidence submit`.",
			Shape:       "output",
			Type:        reflect.TypeFor[EvidenceSubmitResult](),
		},
		{
			Key:         "inputs.review.spec",
			Group:       "command_inputs",
			Path:        "schema/inputs/review.spec.schema.json",
			Title:       "Review start input",
			Description: "JSON input consumed by `harness review start`.",
			Shape:       "input",
			Type:        reflect.TypeFor[ReviewSpec](),
		},
		{
			Key:         "inputs.review.submission",
			Group:       "command_inputs",
			Path:        "schema/inputs/review.submission.schema.json",
			Title:       "Review submission input",
			Description: "JSON input consumed by `harness review submit`.",
			Shape:       "input",
			Type:        reflect.TypeFor[ReviewSubmissionInput](),
		},
		{
			Key:         "inputs.evidence.ci",
			Group:       "command_inputs",
			Path:        "schema/inputs/evidence.ci.schema.json",
			Title:       "CI evidence input",
			Description: "JSON input consumed by `harness evidence submit --kind ci`.",
			Shape:       "input",
			Type:        reflect.TypeFor[EvidenceCIInput](),
		},
		{
			Key:         "inputs.evidence.publish",
			Group:       "command_inputs",
			Path:        "schema/inputs/evidence.publish.schema.json",
			Title:       "Publish evidence input",
			Description: "JSON input consumed by `harness evidence submit --kind publish`.",
			Shape:       "input",
			Type:        reflect.TypeFor[EvidencePublishInput](),
		},
		{
			Key:         "inputs.evidence.sync",
			Group:       "command_inputs",
			Path:        "schema/inputs/evidence.sync.schema.json",
			Title:       "Sync evidence input",
			Description: "JSON input consumed by `harness evidence submit --kind sync`.",
			Shape:       "input",
			Type:        reflect.TypeFor[EvidenceSyncInput](),
		},
		{
			Key:         "artifacts.timeline_event",
			Group:       "artifacts",
			Path:        "schema/artifacts/timeline-event.schema.json",
			Title:       "Timeline event artifact line",
			Description: "One append-only JSONL event line from `.local/harness/plans/<plan-stem>/events.jsonl`.",
			Shape:       "artifact",
			Type:        reflect.TypeFor[TimelineEvent](),
		},
		{
			Key:         "artifacts.current_plan",
			Group:       "artifacts",
			Path:        "schema/artifacts/current-plan.schema.json",
			Title:       "Current plan pointer file",
			Description: "Worktree-level pointer artifact at `.local/harness/current-plan.json`.",
			Shape:       "artifact",
			Type:        reflect.TypeFor[CurrentPlanFile](),
		},
		{
			Key:         "artifacts.local_state",
			Group:       "artifacts",
			Path:        "schema/artifacts/local-state.schema.json",
			Title:       "Plan-local state file",
			Description: "Plan-local runtime state artifact at `.local/harness/plans/<plan-stem>/state.json`.",
			Shape:       "artifact",
			Type:        reflect.TypeFor[LocalStateFile](),
		},
		{
			Key:         "artifacts.review_manifest",
			Group:       "artifacts",
			Path:        "schema/artifacts/review-manifest.schema.json",
			Title:       "Review manifest artifact",
			Description: "Command-owned review manifest artifact for one review round.",
			Shape:       "artifact",
			Type:        reflect.TypeFor[ReviewManifest](),
		},
		{
			Key:         "artifacts.review_ledger",
			Group:       "artifacts",
			Path:        "schema/artifacts/review-ledger.schema.json",
			Title:       "Review ledger artifact",
			Description: "Command-owned review ledger artifact for one review round.",
			Shape:       "artifact",
			Type:        reflect.TypeFor[ReviewLedger](),
		},
		{
			Key:         "artifacts.review_submission",
			Group:       "artifacts",
			Path:        "schema/artifacts/review-submission.schema.json",
			Title:       "Review submission artifact",
			Description: "Command-owned reviewer submission artifact.",
			Shape:       "artifact",
			Type:        reflect.TypeFor[ReviewSubmission](),
		},
		{
			Key:         "artifacts.review_aggregate",
			Group:       "artifacts",
			Path:        "schema/artifacts/review-aggregate.schema.json",
			Title:       "Review aggregate artifact",
			Description: "Command-owned review aggregate artifact.",
			Shape:       "artifact",
			Type:        reflect.TypeFor[ReviewAggregate](),
		},
		{
			Key:         "artifacts.evidence_ci_record",
			Group:       "artifacts",
			Path:        "schema/artifacts/evidence-ci-record.schema.json",
			Title:       "CI evidence record artifact",
			Description: "Command-owned CI evidence artifact.",
			Shape:       "artifact",
			Type:        reflect.TypeFor[EvidenceCIRecord](),
		},
		{
			Key:         "artifacts.evidence_publish_record",
			Group:       "artifacts",
			Path:        "schema/artifacts/evidence-publish-record.schema.json",
			Title:       "Publish evidence record artifact",
			Description: "Command-owned publish evidence artifact.",
			Shape:       "artifact",
			Type:        reflect.TypeFor[EvidencePublishRecord](),
		},
		{
			Key:         "artifacts.evidence_sync_record",
			Group:       "artifacts",
			Path:        "schema/artifacts/evidence-sync-record.schema.json",
			Title:       "Sync evidence record artifact",
			Description: "Command-owned sync evidence artifact.",
			Shape:       "artifact",
			Type:        reflect.TypeFor[EvidenceSyncRecord](),
		},
		{
			Key:         "shared.next_action",
			Group:       "shared",
			Path:        "schema/shared/next-action.schema.json",
			Title:       "Next action",
			Description: "Reusable next-action shape embedded in multiple command results.",
			Shape:       "output",
			Type:        reflect.TypeFor[NextAction](),
		},
		{
			Key:         "shared.error_detail",
			Group:       "shared",
			Path:        "schema/shared/error-detail.schema.json",
			Title:       "Error detail",
			Description: "Reusable path-plus-message error shape embedded in multiple command results.",
			Shape:       "output",
			Type:        reflect.TypeFor[ErrorDetail](),
		},
	}
}
